package com.adminrec.tfi.util.enums;

public enum Permiso {
    ADREC01_MANAGE_EMPLOYEE,
    ADREC02_MANAGE_JOB,
    ADREC03_CONSULT_SECTOR,
    ADREC04_ASSIGN_SUPERVISOR,
    ADREC05_REGISTER_ATTENDANCE,
    ADREC06_CREATE_REQUEST,
    ADREC07_MANAGE_REQUEST,
    ADREC08_CALCULATE_SALARIES,
    ADREC09_GENERATE_REPORT,
}
